### ISSUE TITLE
Modèle Utilisateur

### ISSUE THREAD

**Issue by mdevoldere** [kyweez/CDA-02-LanChat-BBT#4]
Un utilisateur est caractérisé par les attributs suivants: **username**, **password**, **email**, **creationDate**, **lastLogged** et **isLogged**.

Déterminer le type de chacun des attributs et modéliser la classe "User".

**Comment by titibrown** [comment]
Donc Si je comprend bien, je vais créer une classe User ? :)

**Comment by kyweez** [comment]
Oui ! Et une serie de tests qui vont avec ! Dans un premier temps !

**Comment by mdevoldere** [comment]
Dans le répertoire /tests/ créer un fichier user_tests.js.
Importer la classe User.
Créer quelques utilisateurs et les afficher dans la console.

**Comment by titibrown** [comment]
Je vais essayer de finir la Class User aujourd'hui .

**Comment by kyweez** [comment]
> Je vais essayer de finir la Class User aujourd'hui .

Pas de pression  hein !

**Comment by titibrown** [comment]
J'ai été quelque chose , en sachant que vis-à-vis de l'email, Mickael m'a dit qu'il fallait procéder plus simplement avec une adresse mail que l'utilisateur fourni lui-même.
